[package]
cairo-version = "=2.8.4"
name = "sn_simple"
version = "0.1.0"
edition = "2024_07"

[dependencies]
dojo = { path = "../../crates/contracts" }
dojo_macros = { path = "../../crates/macros" }

[[target.starknet-contract]]

[features]
default = []
